name: Check Branch Before Merge

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check if branch is allowed
      run: |
        disallowed_branches=("main" "master" "develop" "Atharv" "dump_files_atharv" "development" "Production")
        branch_name="${GITHUB_HEAD_REF##*/}"
        
        if [[ " ${disallowed_branches[@]} " =~ " $branch_name " ]]; then
          echo "Branch $branch_name is not allowed for direct merging into Full_Course."
          exit 1
        else
          echo "Branch $branch_name is allowed for merging into Full_Course."
        fi
        
    - name: Check if PR is raised against allowed branches
      run: |
        disallowed_branches=("main" "master" "develop" "development" "Production")
        pr_branch_name="${GITHUB_BASE_REF}"
        
        if [[ " ${disallowed_branches[@]} " =~ " $pr_branch_name " ]]; then
          echo "Pull request is raised against disallowed branch $pr_branch_name."
          exit 1
        else
          echo "Pull request is raised against allowed branch $pr_branch_name."
        fi
